name: Test Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # 1️⃣ Checar repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Instalar dependências
      - name: Install dependencies
        run: npm install
        working-directory: backend

      # 4️⃣ Exportar variáveis de ambiente efêmeras
      - name: Export ephemeral env vars
        run: |
          echo "JWT_SECRET=$(openssl rand -hex 32)" >> $GITHUB_ENV
          echo "PORT=4000" >> $GITHUB_ENV
          echo "CORS_ORIGIN=http://localhost:5173" >> $GITHUB_ENV
        working-directory: backend

      # 5️⃣ Rodar testes unitários
      - name: Run backend unit tests
        run: npm test
        working-directory: backend

      # 6️⃣ Mensagem de sucesso
      - name: Success
        run: echo 'CI tests passed-> backend tests for all roles succeeded!'
